<a href="https://colab.research.google.com/github/Hercules2310/Real_estate_price_prediction/blob/main/Independent_Houses_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import librariies
import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings("ignore")

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
houses=pd.read_csv('https://raw.githubusercontent.com/Hercules2310/Real_estate_price_prediction/main/independent-house%20-%20independent-house.csv')

In [4]:
houses.columns

Index(['property_name', 'link', 'society', 'price', 'rate', 'area',
       'areaWithType', 'bedRoom', 'bathroom', 'balcony', 'additionalRoom',
       'address', 'noOfFloor', 'facing', 'agePossession', 'nearbyLocations',
       'description', 'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')

In [5]:
houses.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [6]:
houses.shape

(968, 21)

In [7]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    968 non-null    object
 1   link             968 non-null    object
 2   society          391 non-null    object
 3   price            968 non-null    object
 4   rate             958 non-null    object
 5   area             968 non-null    object
 6   areaWithType     968 non-null    object
 7   bedRoom          968 non-null    object
 8   bathroom         968 non-null    object
 9   balcony          968 non-null    object
 10  additionalRoom   577 non-null    object
 11  address          963 non-null    object
 12  noOfFloor        948 non-null    object
 13  facing           661 non-null    object
 14  agePossession    968 non-null    object
 15  nearbyLocations  846 non-null    object
 16  description      968 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         659 non-null    object
 19  rating           847 non-null    object
 20  property_id      968 non-null    object
dtypes: object(21)
memory usage: 158.9+ KB

In [8]:
houses.isna().sum()

property_name        0
link                 0
society            577
price                0
rate                10
area                 0
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom     391
address              5
noOfFloor           20
facing             307
agePossession        0
nearbyLocations    122
description          0
furnishDetails     239
features           309
rating             121
property_id          0
dtype: int64

In [9]:
houses.duplicated().sum()

13

In [10]:
houses=houses.drop_duplicates()

In [11]:
houses.shape

(955, 21)

In [12]:
houses.sample(2)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
284,2 Bedroom House for sale in Sheetla Colony,https://www.99acres.com/2-bhk-bedroom-independ...,NaN,70 Lac,"₹ 7,701/sq.ft.",(84 sq.m.) Plot Area,Plot area 101(84.45 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,House No 32 Block A Gali No 5 Sheetla Enclave ...,1 Floors,North-East,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","2 bath, semi-Furnished, ground floor (Of 1), o...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Water purifier',...","['Environment3 out of 5', 'Lifestyle3 out of 5...",X66250392
865,9 Bedroom House for sale in C Block Sushant Lo...,https://www.99acres.com/9-bhk-bedroom-independ...,NaN,5.3 Crore,"₹ 27,390/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,Servant Room,"C Block, C Block Sushant Lok Phase 1, Gurgaon,...",3 Floors,East,5 to 10 Year Old,"['Sector 42-43 metro station', 'Huda city cent...",This property is available at c block with eas...,"['9 Wardrobe', '15 Fan', '1 Exhaust Fan', '12 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ...",A69556196

In [13]:
houses.drop(['link','property_id'],axis=1,inplace=True)

In [14]:
houses.rename(columns={'rate':'price_per_sqft','noOfFloor':'floorNum'},inplace=True)

In [15]:
houses.shape

(955, 19)

In [16]:
houses['society'].value_counts().shape

(180,)

In [17]:
houses['society'].value_counts()

society
International City by SOBHA Phase 2                  19
Vipul Tatvam Villa                                   19
International City by Sobha Phase 1                  15
Emaar MGF Marbella                                   13
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Uniworld Resorts                             10
Unitech Espace                                       10
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   7
Ansals Palam Vihar                                    6
Eldeco Mansionz                                       6
Not Applicable                                        6
Sushant Lok 1 Builder Floors                          6
DLF City Phase 1                                      5
Ansal Sushant Lok Plots4.1 ★                          4
Unitech Aspen Greens                                  4
nul                                                   4
Vatika India Next4.1 ★                                4
Vatika Signature Villas                               3
SS Aaron Ville                                        3
Palam Vihar Extension West Zone RWA                   3
Malibu Towne                                          3
Sector 14 RWA                                         3
Rattan Garden                                         3
Housing Board Colony                                  3
Eros Rosewood City4.0 ★                               3
Experion Windchants3.8 ★                              3
BPTP Astaire Gardens3.7 ★                             3
Eros Rosewood Villas                                  3
DLF City Plots Phase 3                                3
Ansals Florence Villa                                 3
DLF New Town Heights 24.0 ★                           3
Unitech Nirvana Birch Court                           3
Sector 38 RWA                                         2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
RWA Sector 46                                         2
BPTP Pedestal                                         2
Ardee City3.8 ★                                       2
Unitech Palms South City 1                            2
Project Mianwali Colony                               2
Unitech Escape3.8 ★                                   2
Tata Primanti4.1 ★                                    2
Satya The Hermitage3.5 ★                              2
Hans Enclave                                          2
Suncity Township4.1 ★                                 2
SS Hibiscus                                           2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Project Housing Board Colony                          2
Silverglades Tarudhan Valley Golf Resort              2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Ansal API Esencia3.7 ★                                2
Unitech Deerwood Chase                                2
Suncity Essel Towers4.2 ★                             2
Luxury DLF City Floors                                2
Smart World Orchard                                   1
Ansal Florence Super                                  1
Ireo Victory Valley4.1 ★                              1
private house                                         1
Ashok Vihar Phase 3 Gurgaon                           1
4S Aradhya Homes                                      1
Ansal API Spanish Court                               1
Emaar Emerald Hills4.1 ★                              1
Unitech South City 23.8 ★                             1
Sector-17C                                            1
Central Park Flower Valley Cerise Floors              1
HUDA Ashok Vihar Phase 13.9 ★                         1
Om Nagar, Sector-11                                   1
Birla Navya                                           1
DLF Floors Phase 3                                    1
Kothi                                                 1
Farrukhnagar                                          1
Prem Kunj                                             1
DLF City Plots Phase 4                                1
nirvana country                                       1
Landmark House                                        1
secter 16a daultabad faridabad house no 313           1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
huda sector-56 gurgaon                                1
Puri Diplomatic Greens4.0 ★                           1
Ansal Sushant Residency                               1
rajendra park sec 105                                 1
Huda Floor                                            1
Huda                                                  1
Sector 57 Huda                                        1
Saksham Welfare Association                           1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Grover Homes Sec 4                                    1
Central Park Flower Valley                            1
DLF Pink Town House4.0 ★                              1
FLOOR WISE DESIGNER KOTHI                             1
Satya The Legend3.8 ★                                 1
Bestech Park View Ananda4.2 ★                         1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
DLF Alameda                                           1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF South City 1                                      1
Ashok vihar phase III Extension                       1
rattan vihar rajendra park                            1
DLF The Arbour                                        1
Anant Raj Estates                                     1
HUDA Plot Sector 38                                   1
DLF Gardencity Enclave                                1
mian wali                                             1
Shri Shyam Residency                                  1
Ansal Celebrity Homes                                 1
Laxmi Garden Sector-11                                1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Signature Global City 63A                             1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
ATS Tourmaline3.9 ★                                   1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Bhawani enclave                                       1
Huda Plots                                            1
DLF Garden City Floors                                1
ROW HOUSE                                             1
Surat nagar phase 2                                   1
Madan puri                                            1
Indiabulls Centrum Park3.7 ★                          1
Adani Brahma Samsara4.2 ★                             1
sneh vihar                                            1
Sheetla Enclave                                       1
Suncity Avenue 76                                     1
SS Omnia                                              1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
Ansal Heights3.2 ★                                    1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Sobha City                                            1
Raj Villas                                            1
Ninex City                                            1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Signature Global Park4.0 ★                            1
Krishna Palace                                        1
My Home                                               1
Huda Flats                                            1
Jacobpura                                             1
Naman Residency                                       1
Name: count, dtype: int64

In [18]:
houses['society']=houses['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★?','',str(name).strip())).str.lower()

In [19]:
houses['society'].value_counts().shape

(174,)

In [20]:
houses['price']

0            5.25 Crore
1             5.7 Crore
2             2.1 Crore
3               5 Crore
4               3 Crore
5             4.5 Crore
6              12 Crore
7              20 Crore
8           10.85 Crore
9            1.95 Crore
10           4.45 Crore
11              9 Crore
12              5 Crore
13             15 Crore
14           8.25 Crore
15              2 Crore
16          10.75 Crore
17            2.1 Crore
18           7.35 Crore
19           4.45 Crore
20            3.4 Crore
21             12 Crore
22            8.4 Crore
23            8.5 Crore
24            7.6 Crore
25              7 Crore
26           4.75 Crore
27            3.5 Crore
28              5 Crore
29          10.56 Crore
30           5.46 Crore
31             10 Crore
32              9 Crore
33             10 Crore
34           1.95 Crore
35            3.3 Crore
36             13 Crore
37            7.2 Crore
38              6 Crore
39              9 Crore
40            5.8 Crore
41            55.11 Lac
42           7.49 Crore
43           13.5 Crore
44          11.95 Crore
45          12.39 Crore
46           6.25 Crore
47            5.4 Crore
48           5.75 Crore
49           2.55 Crore
50            5.6 Crore
51             17 Crore
52           7.99 Crore
53           3.75 Crore
54           7.25 Crore
55            8.4 Crore
56           3.55 Crore
57            2.5 Crore
58            2.5 Crore
59              9 Crore
60            2.1 Crore
61            4.5 Crore
62            6.5 Crore
63            9.5 Crore
64              5 Crore
65            5.5 Crore
66           5.65 Crore
67            8.8 Crore
68           3.25 Crore
69              5 Crore
70          10.45 Crore
71           19.5 Crore
72            7.5 Crore
73               67 Lac
74           5.75 Crore
75            5.7 Crore
76            3.2 Crore
77           11.5 Crore
78           7.69 Crore
79              7 Crore
80           1.55 Crore
81           3.85 Crore
82              2 Crore
83            3.1 Crore
84           2.25 Crore
85              7 Crore
86            8.5 Crore
87            8.7 Crore
88           12.5 Crore
89            6.8 Crore
90            9.5 Crore
91              7 Crore
92            6.2 Crore
93            3.6 Crore
94           3.05 Crore
95            5.9 Crore
96           5.85 Crore
97              4 Crore
98           5.35 Crore
99            6.6 Crore
100           6.3 Crore
101            12 Crore
102              65 Lac
103              55 Lac
104              85 Lac
105              58 Lac
106              65 Lac
107              61 Lac
108              67 Lac
109           5.8 Crore
110             6 Crore
111          6.25 Crore
112          7.05 Crore
113           4.5 Crore
114          3.69 Crore
115           2.5 Crore
116           5.5 Crore
117            15 Crore
118          6.95 Crore
119           5.7 Crore
120          11.3 Crore
121         11.25 Crore
122          4.02 Crore
123           5.7 Crore
124             1 Crore
125              66 Lac
126              70 Lac
127          1.45 Crore
128              95 Lac
129           4.5 Crore
130              90 Lac
131              45 Lac
132             1 Crore
133              60 Lac
134             7 Crore
135          3.93 Crore
136             4 Crore
137              75 Lac
138              90 Lac
139          2.75 Crore
140              50 Lac
141              50 Lac
142              42 Lac
143              60 Lac
144              48 Lac
145              50 Lac
146              35 Lac
147             4 Crore
148           2.4 Crore
149           2.2 Crore
150           1.1 Crore
151             8 Crore
152              82 Lac
153              90 Lac
154              70 Lac
155              95 Lac
156           1.3 Crore
157              36 Lac
158           3.5 Crore
159              80 Lac
160            15.5 Lac
161              80 Lac
162             6 Crore
163           2.8 Crore
164          2.75 Crore
165          1.75 Crore
166           3.1 Crore
167          1.16 Crore
168              85 Lac
169              90 Lac
170              34 Lac
171             5 Crore
172              36 Lac
173             5 Crore
174           9.5 Crore
175          7.25 Crore
176           1.5 Crore
177           1.3 Crore
178          3.75 Crore
179              37 Lac
180          2.25 Crore
181          1.15 Crore
182              95 Lac
183              49 Lac
184          1.45 Crore
185              80 Lac
186           1.6 Crore
187              85 Lac
188             7 Crore
189              50 Lac
190             8 Crore
191              45 Lac
192              62 Lac
193             1 Crore
194          4.12 Crore
195              95 Lac
196              45 Lac
197              45 Lac
198          1.87 Crore
199              85 Lac
200              42 Lac
201              42 Lac
202           1.2 Crore
203           6.5 Crore
204          3.75 Crore
205           2.5 Crore
206          2.25 Crore
207              75 Lac
208              30 Lac
209          1.35 Crore
210           4.7 Crore
211              60 Lac
212              22 Lac
213          1.65 Crore
214              50 Lac
215           2.3 Crore
216          1.25 Crore
217           1.7 Crore
218    Price on Request
219    Price on Request
220             6 Crore
221           2.8 Crore
222          3.12 Crore
223             7.5 Lac
224           3.5 Crore
225          2.58 Crore
226           8.5 Crore
227             4 Crore
228          1.45 Crore
229              60 Lac
230           1.1 Crore
231           2.5 Crore
232           3.5 Crore
233          2.95 Crore
234              70 Lac
235          1.16 Crore
236            16 Crore
237           8.5 Crore
238          8.95 Crore
239            14 Crore
240              85 Lac
241          1.35 Crore
242          13.2 Crore
243             6 Crore
244    Price on Request
245    Price on Request
246              51 Lac
247           1.1 Crore
248           2.5 Crore
249              53 Lac
250             2 Crore
251              63 Lac
252             8 Crore
253              45 Lac
254              37 Lac
255          1.72 Crore
256          1.35 Crore
257              50 Lac
258              62 Lac
259             8 Crore
260           1.8 Crore
261           1.7 Crore
262              55 Lac
263           1.5 Crore
264          1.55 Crore
265              32 Lac
266           2.1 Crore
267           5.6 Crore
268              65 Lac
269           1.6 Crore
270              78 Lac
271              95 Lac
272          3.85 Crore
273              66 Lac
274              45 Lac
275              85 Lac
276           1.5 Crore
277          1.52 Crore
278             1 Crore
279          1.05 Crore
280              85 Lac
281              58 Lac
282              45 Lac
283          1.35 Crore
284              70 Lac
285           1.4 Crore
286          5.15 Crore
287           6.5 Crore
288           3.5 Crore
289          13.5 Crore
290           5.7 Crore
291           3.3 Crore
292          1.75 Crore
293              75 Lac
294           3.5 Crore
295              92 Lac
296    Price on Request
297              52 Lac
298           1.1 Crore
299              75 Lac
300          1.25 Crore
301          4.25 Crore
302              37 Lac
303           5.7 Crore
304              80 Lac
305           2.1 Crore
306           1.1 Crore
307              60 Lac
308           1.2 Crore
309           4.5 Crore
310              80 Lac
311           1.1 Crore
312             3 Crore
313           8.5 Crore
314           1.1 Crore
315              75 Lac
316             6 Crore
317              82 Lac
318              35 Lac
319          1.15 Crore
320          1.85 Crore
321           8.5 Crore
322              90 Lac
323              50 Lac
324    Price on Request
325          5.75 Crore
326          4.65 Crore
327           7.2 Crore
328              60 Lac
329           4.5 Crore
330           1.3 Crore
331           3.2 Crore
332              60 Lac
333          1.95 Crore
334          1.25 Crore
335           6.1 Crore
336              50 Lac
337             2 Crore
338           2.1 Crore
339          1.25 Crore
340              65 Lac
341          11.5 Crore
342              90 Lac
343              75 Lac
344           1.3 Crore
345              48 Lac
346              68 Lac
347           1.5 Crore
348           1.3 Crore
349              60 Lac
350           6.5 Crore
351              49 Lac
352          1.07 Crore
353           2.1 Crore
354           4.6 Crore
355             1 Crore
356           1.1 Crore
357          2.95 Crore
358           4.6 Crore
359              35 Lac
360           1.5 Crore
361            10 Crore
362           5.2 Crore
363              40 Lac
364              62 Lac
365              50 Lac
366             5 Crore
367              92 Lac
368           3.5 Crore
369              80 Lac
370           1.5 Crore
371          2.25 Crore
372          13.5 Crore
373              50 Lac
374           1.7 Crore
375              45 Lac
376           1.2 Crore
377           1.8 Crore
378           1.5 Crore
379              35 Lac
380              55 Lac
381           4.3 Crore
382              40 Lac
383             3 Crore
384           42.75 Lac
385    Price on Request
386              32 Lac
387              47 Lac
388           5.5 Crore
389              75 Lac
390              71 Lac
391              38 Lac
392          3.25 Crore
393            52.5 Lac
394           2.3 Crore
395           1.5 Crore
396           1.1 Crore
397          1.35 Crore
398           1.3 Crore
399          1.25 Crore
400          1.44 Crore
401              50 Lac
402             1 Crore
403           5.5 Crore
404           5.5 Crore
405              80 Lac
406              90 Lac
407           4.3 Crore
408              90 Lac
409          3.25 Crore
410              38 Lac
411          3.71 Crore
412            13 Crore
413              40 Lac
414              55 Lac
415           1.3 Crore
416              75 Lac
417              30 Lac
418              18 Lac
419          1.55 Crore
420              32 Lac
421             4 Crore
422              38 Lac
423            12 Crore
424             8 Crore
425              45 Lac
426           1.2 Crore
427              40 Lac
428             1 Crore
429              50 Lac
430          1.15 Crore
431              70 Lac
432          3.08 Crore
433          2.95 Crore
434             8 Crore
435           6.5 Crore
436             3 Crore
437             8 Crore
438          2.75 Crore
439          2.25 Crore
440          1.45 Crore
441           3.5 Crore
442              82 Lac
443          10.5 Crore
444              38 Lac
445            10 Crore
446              75 Lac
447           4.6 Crore
448              50 Lac
449             7 Crore
450              35 Lac
451              95 Lac
452           1.6 Crore
453              29 Lac
454              24 Lac
455           5.6 Crore
456              55 Lac
457             5 Crore
458           1.8 Crore
459    Price on Request
460           1.5 Crore
461          1.05 Crore
462           1.8 Crore
463              44 Lac
464              83 Lac
465              70 Lac
466              98 Lac
467          3.35 Crore
468            47.5 Lac
469           1.2 Crore
470             9 Crore
471          3.09 Crore
472          3.15 Crore
473           1.7 Crore
474          4.75 Crore
475          1.65 Crore
476              85 Lac
477             2 Crore
478              74 Lac
479          1.85 Crore
480              40 Lac
481              85 Lac
482              69 Lac
483              85 Lac
484            13 Crore
485    Price on Request
486           1.4 Crore
487           1.8 Crore
488              70 Lac
489              70 Lac
490           2.4 Crore
491          3.35 Crore
492             7 Crore
493          1.65 Crore
494              60 Lac
495          2.43 Crore
496           3.5 Crore
497              34 Lac
498              75 Lac
499              55 Lac
500              70 Lac
501          6.25 Crore
502           1.2 Crore
503              49 Lac
504             2 Crore
505              37 Lac
506              42 Lac
507              75 Lac
508           3.5 Crore
509           4.5 Crore
510          1.16 Crore
511              90 Lac
512              75 Lac
513              13 Lac
514              96 Lac
515          1.35 Crore
516              65 Lac
517            11 Crore
518         18.02 Crore
519            65.8 Lac
520           4.6 Crore
521           1.9 Crore
522           1.5 Crore
523           2.5 Crore
524              70 Lac
525              85 Lac
526             2 Crore
527              70 Lac
528              89 Lac
529              80 Lac
530           1.6 Crore
531              89 Lac
532          1.34 Crore
533           1.7 Crore
534              34 Lac
535           9.9 Crore
536              40 Lac
537          2.15 Crore
538          1.85 Crore
539              45 Lac
540           58.25 Lac
541           1.7 Crore
542              46 Lac
543              80 Lac
544           58.25 Lac
545           2.6 Crore
546             2 Crore
547          3.87 Crore
548              65 Lac
549          2.25 Crore
550              85 Lac
551             2 Crore
552            10 Crore
553           3.5 Crore
554              55 Lac
555           6.5 Crore
556          1.39 Crore
557    Price on Request
558              70 Lac
559              59 Lac
560             4 Crore
561          12.5 Crore
562           1.6 Crore
563           1.6 Crore
564           2.9 Crore
565              40 Lac
566           1.7 Crore
567           5.5 Crore
568          6.75 Crore
569           5.5 Crore
570          2.75 Crore
571              27 Lac
572              70 Lac
573              95 Lac
574           8.1 Crore
575             7 Crore
576              38 Lac
577              60 Lac
578              65 Lac
579           7.2 Crore
580           1.5 Crore
581            10 Crore
582          15.5 Crore
583         14.75 Crore
584            20 Crore
585          9.54 Crore
586         10.55 Crore
587          17.3 Crore
588          3.65 Crore
589          18.9 Crore
590             9 Crore
591            24 Crore
592          2.15 Crore
593          2.25 Crore
594          7.46 Crore
595          6.75 Crore
596           59.95 Lac
597          3.99 Crore
598          6.81 Crore
599           6.5 Crore
600          6.95 Crore
601             7 Crore
602          3.85 Crore
603           3.2 Crore
604          8.81 Crore
605          1.45 Crore
606           8.9 Crore
607           6.5 Crore
608          4.49 Crore
609            22 Crore
610           9.5 Crore
611             7 Crore
612          4.15 Crore
613           2.9 Crore
614            12 Crore
615           8.5 Crore
616            11 Crore
617          1.35 Crore
618           1.9 Crore
619          3.25 Crore
620            19 Crore
621           7.3 Crore
622           5.6 Crore
623          2.55 Crore
624           2.4 Crore
625          18.5 Crore
626            26 Crore
627           1.7 Crore
628           1.6 Crore
629          4.35 Crore
630           6.8 Crore
631            10 Crore
632           4.6 Crore
633          12.5 Crore
634           2.9 Crore
635          27.5 Crore
636             8 Crore
637          2.25 Crore
638          8.31 Crore
639          6.21 Crore
640          7.35 Crore
641           4.5 Crore
642           6.5 Crore
643          1.83 Crore
644          7.35 Crore
645          10.5 Crore
646          2.75 Crore
647           6.5 Crore
648           7.5 Crore
649             8 Crore
650           5.5 Crore
651          4.35 Crore
652          2.75 Crore
653            18 Crore
654            17 Crore
655          3.75 Crore
656          13.5 Crore
657          4.75 Crore
658           5.1 Crore
659           3.9 Crore
660          6.25 Crore
661         10.55 Crore
662          2.01 Crore
663          3.25 Crore
664          9.25 Crore
665             6 Crore
666          5.25 Crore
667            26 Crore
668          5.88 Crore
669           52.75 Lac
670           46.75 Lac
671         12.25 Crore
672         10.45 Crore
673            12 Crore
674           6.4 Crore
675          4.35 Crore
676          2.95 Crore
677             3 Crore
678          1.15 Crore
679          8.25 Crore
680          13.5 Crore
681            15 Crore
682           5.5 Crore
683            18 Crore
684           5.8 Crore
685          12.5 Crore
686          3.51 Crore
687           3.5 Crore
688           9.4 Crore
689          10.3 Crore
690             6 Crore
691          8.45 Crore
692          7.25 Crore
693             4 Crore
694          6.15 Crore
695           4.6 Crore
696          12.5 Crore
697            10 Crore
698            16 Crore
699          12.5 Crore
700            16 Crore
701            10 Crore
702           2.8 Crore
703          6.75 Crore
704           2.5 Crore
705             8 Crore
718          2.47 Crore
719           3.7 Crore
720          18.4 Crore
721           4.6 Crore
722          3.65 Crore
723            12 Crore
724           4.5 Crore
725           4.4 Crore
726          7.25 Crore
727              99 Lac
728            20 Crore
729          2.65 Crore
730          2.95 Crore
731           3.6 Crore
732          1.27 Crore
733              75 Lac
734             6 Crore
735           6.5 Crore
736            18 Crore
737         11.29 Crore
738          8.49 Crore
739           8.5 Crore
740             6 Crore
741           9.5 Crore
742          19.5 Crore
743          10.5 Crore
744          4.31 Crore
745          6.95 Crore
746          10.5 Crore
747          10.5 Crore
748           5.8 Crore
749           4.6 Crore
750         11.58 Crore
751             4 Crore
752            16 Crore
753             6 Crore
755           6.8 Crore
756           2.5 Crore
757           7.5 Crore
758          8.48 Crore
759          6.25 Crore
760         10.85 Crore
761          5.15 Crore
762           3.5 Crore
763           3.6 Crore
764             6 Crore
765            14 Crore
766           1.6 Crore
767           1.7 Crore
768          7.25 Crore
769          15.5 Crore
770           3.4 Crore
771         11.25 Crore
772           3.3 Crore
773           5.5 Crore
774           8.5 Crore
775           8.5 Crore
776         11.95 Crore
777            12 Crore
778           6.5 Crore
779            17 Crore
780          11.5 Crore
781             9 Crore
782            15 Crore
783           8.2 Crore
784          5.51 Crore
785           3.2 Crore
786             8 Crore
787          2.95 Crore
788           2.8 Crore
789          5.25 Crore
790          8.49 Crore
791          4.35 Crore
792          3.49 Crore
793          2.99 Crore
794          9.19 Crore
795          1.64 Crore
796          9.35 Crore
797          9.25 Crore
798           2.8 Crore
799           2.5 Crore
800          4.05 Crore
801           8.4 Crore
802             6 Crore
803            11 Crore
804          8.75 Crore
805            23 Crore
806           6.5 Crore
807          2.45 Crore
808           5.5 Crore
809          3.51 Crore
810          9.25 Crore
811          5.65 Crore
812          7.85 Crore
813          13.5 Crore
814            19 Crore
815           5.5 Crore
816           3.5 Crore
817          8.25 Crore
818            16 Crore
819            25 Crore
820          2.68 Crore
821           2.7 Crore
822           2.3 Crore
823              92 Lac
824          1.04 Crore
825          9.85 Crore
826            15 Crore
827          1.18 Crore
828              90 Lac
829            13 Crore
830          15.1 Crore
831          9.01 Crore
832            18 Crore
833            12 Crore
834          2.25 Crore
835             8 Crore
836          5.75 Crore
837           9.8 Crore
838          4.95 Crore
839            19 Crore
840          4.99 Crore
841           7.1 Crore
842          4.25 Crore
843           9.5 Crore
844            16 Crore
845          8.25 Crore

In [21]:
houses[houses['price']=='Price on Request'].shape

(10, 19)

In [22]:
houses.drop(houses[houses['price']=='Price on Request'].index,axis=0,inplace=True)

In [23]:
houses.shape

(945, 19)

In [24]:
houses['price'].isna().sum()

0

In [25]:
houses['price'].str.split().apply(len).value_counts()

price
2    945
Name: count, dtype: int64

In [26]:
houses['price'].str.split().apply(lambda x: x[1]).unique()

array(['Crore', 'Lac'], dtype=object)

In [27]:
def treat_price(x):
  if x[-1]=='Lac':
    return round(float(x[0])/100,2)
  else :
    return round(float(x[0]),2)

In [28]:
houses['price']=houses['price'].str.split().apply(treat_price)

In [29]:
houses['price_per_sqft']

0       ₹ 20,115/sq.ft.
1      ₹ 105,751/sq.ft.
2       ₹ 38,251/sq.ft.
3       ₹ 43,066/sq.ft.
4       ₹ 53,763/sq.ft.
5       ₹ 39,062/sq.ft.
6       ₹ 37,037/sq.ft.
7       ₹ 48,889/sq.ft.
8       ₹ 38,150/sq.ft.
9       ₹ 10,077/sq.ft.
10      ₹ 32,963/sq.ft.
11      ₹ 27,778/sq.ft.
12      ₹ 34,083/sq.ft.
13      ₹ 33,200/sq.ft.
14      ₹ 30,556/sq.ft.
15      ₹ 14,914/sq.ft.
16      ₹ 29,861/sq.ft.
17      ₹ 23,333/sq.ft.
18      ₹ 41,762/sq.ft.
19      ₹ 15,451/sq.ft.
20      ₹ 12,938/sq.ft.
21      ₹ 38,095/sq.ft.
22      ₹ 25,926/sq.ft.
23      ₹ 26,235/sq.ft.
24      ₹ 38,760/sq.ft.
25      ₹ 25,926/sq.ft.
26       ₹ 9,374/sq.ft.
27      ₹ 13,410/sq.ft.
28      ₹ 21,124/sq.ft.
29      ₹ 32,593/sq.ft.
30      ₹ 24,170/sq.ft.
31      ₹ 37,037/sq.ft.
32      ₹ 28,490/sq.ft.
33     ₹ 122,222/sq.ft.
34      ₹ 13,542/sq.ft.
35      ₹ 19,097/sq.ft.
36      ₹ 48,148/sq.ft.
37      ₹ 22,222/sq.ft.
38      ₹ 22,222/sq.ft.
39      ₹ 33,333/sq.ft.
40      ₹ 32,222/sq.ft.
41       ₹ 7,290/sq.ft.
42      ₹ 27,741/sq.ft.
43      ₹ 50,000/sq.ft.
44      ₹ 43,534/sq.ft.
45      ₹ 45,889/sq.ft.
46      ₹ 34,722/sq.ft.
47      ₹ 20,690/sq.ft.
48      ₹ 29,716/sq.ft.
49      ₹ 16,378/sq.ft.
50      ₹ 17,284/sq.ft.
51      ₹ 37,777/sq.ft.
52      ₹ 12,519/sq.ft.
53      ₹ 25,562/sq.ft.
54      ₹ 27,971/sq.ft.
55      ₹ 21,000/sq.ft.
56      ₹ 24,500/sq.ft.
57       ₹ 7,058/sq.ft.
58       ₹ 7,058/sq.ft.
59      ₹ 11,250/sq.ft.
60      ₹ 23,333/sq.ft.
61      ₹ 20,000/sq.ft.
62      ₹ 35,400/sq.ft.
63      ₹ 40,135/sq.ft.
64      ₹ 16,244/sq.ft.
65      ₹ 21,605/sq.ft.
66      ₹ 10,463/sq.ft.
67      ₹ 41,615/sq.ft.
68      ₹ 14,444/sq.ft.
69      ₹ 10,101/sq.ft.
70      ₹ 38,703/sq.ft.
71      ₹ 22,222/sq.ft.
72      ₹ 23,148/sq.ft.
73       ₹ 8,557/sq.ft.
74      ₹ 16,428/sq.ft.
75      ₹ 10,556/sq.ft.
76      ₹ 13,519/sq.ft.
77      ₹ 42,032/sq.ft.
78      ₹ 24,069/sq.ft.
79      ₹ 21,605/sq.ft.
80      ₹ 13,889/sq.ft.
81      ₹ 14,650/sq.ft.
82      ₹ 13,889/sq.ft.
83      ₹ 13,778/sq.ft.
84      ₹ 15,625/sq.ft.
85      ₹ 23,333/sq.ft.
86      ₹ 21,250/sq.ft.
87      ₹ 38,667/sq.ft.
88      ₹ 26,667/sq.ft.
89      ₹ 12,593/sq.ft.
90      ₹ 26,389/sq.ft.
91      ₹ 12,963/sq.ft.
92      ₹ 25,514/sq.ft.
93      ₹ 24,845/sq.ft.
94      ₹ 17,650/sq.ft.
95      ₹ 24,280/sq.ft.
96      ₹ 26,423/sq.ft.
97       ₹ 6,666/sq.ft.
98       ₹ 8,916/sq.ft.
99      ₹ 36,667/sq.ft.
100      ₹ 9,000/sq.ft.
101     ₹ 20,000/sq.ft.
102      ₹ 9,028/sq.ft.
103      ₹ 4,074/sq.ft.
104        ₹ 630/sq.ft.
105     ₹ 86,567/sq.ft.
106     ₹ 92,857/sq.ft.
107    ₹ 100,000/sq.ft.
108     ₹ 88,157/sq.ft.
109     ₹ 29,974/sq.ft.
110     ₹ 24,691/sq.ft.
111      ₹ 2,778/sq.ft.
112     ₹ 46,906/sq.ft.
113     ₹ 25,000/sq.ft.
114     ₹ 23,699/sq.ft.
115     ₹ 25,960/sq.ft.
116     ₹ 28,424/sq.ft.
117     ₹ 33,333/sq.ft.
118      ₹ 4,490/sq.ft.
119     ₹ 14,729/sq.ft.
120     ₹ 25,111/sq.ft.
121     ₹ 25,000/sq.ft.
122      ₹ 7,309/sq.ft.
123     ₹ 10,556/sq.ft.
124     ₹ 74,074/sq.ft.
125     ₹ 12,000/sq.ft.
126     ₹ 10,233/sq.ft.
127     ₹ 26,852/sq.ft.
128      ₹ 8,878/sq.ft.
129     ₹ 14,286/sq.ft.
130      ₹ 8,928/sq.ft.
131      ₹ 8,007/sq.ft.
132     ₹ 11,111/sq.ft.
133      ₹ 5,698/sq.ft.
134     ₹ 28,283/sq.ft.
135     ₹ 24,214/sq.ft.
136     ₹ 26,613/sq.ft.
137    ₹ 138,888/sq.ft.
138     ₹ 10,000/sq.ft.
139      ₹ 7,666/sq.ft.
140      ₹ 7,407/sq.ft.
141      ₹ 8,333/sq.ft.
142      ₹ 4,666/sq.ft.
143     ₹ 13,333/sq.ft.
144     ₹ 60,000/sq.ft.
145     ₹ 11,111/sq.ft.
146      ₹ 7,778/sq.ft.
147     ₹ 40,775/sq.ft.
148     ₹ 99,173/sq.ft.
149     ₹ 12,222/sq.ft.
150      ₹ 6,172/sq.ft.
151     ₹ 22,222/sq.ft.
152      ₹ 9,111/sq.ft.
153     ₹ 80,357/sq.ft.
154      ₹ 4,117/sq.ft.
155      ₹ 7,308/sq.ft.
156      ₹ 8,701/sq.ft.
157      ₹ 8,000/sq.ft.
158     ₹ 25,926/sq.ft.
159      ₹ 6,666/sq.ft.
160      ₹ 2,296/sq.ft.
161      ₹ 8,888/sq.ft.
162     ₹ 33,333/sq.ft.
163     ₹ 12,444/sq.ft.
164      ₹ 9,793/sq.ft.
165      ₹ 6,250/sq.ft.
166      ₹ 8,486/sq.ft.
167     ₹ 11,717/sq.ft.
168      ₹ 7,589/sq.ft.
169     ₹ 13,333/sq.ft.
170     ₹ 12,592/sq.ft.
171     ₹ 15,384/sq.ft.
172      ₹ 7,843/sq.ft.
173     ₹ 22,222/sq.ft.
174     ₹ 23,333/sq.ft.
175     ₹ 29,336/sq.ft.
176     ₹ 10,288/sq.ft.
177     ₹ 11,284/sq.ft.
178     ₹ 11,029/sq.ft.
179     ₹ 10,277/sq.ft.
180      ₹ 6,944/sq.ft.
181      ₹ 8,518/sq.ft.
182     ₹ 10,555/sq.ft.
183     ₹ 11,250/sq.ft.
184        ₹ 557/sq.ft.
185      ₹ 8,888/sq.ft.
186     ₹ 11,852/sq.ft.
187      ₹ 8,947/sq.ft.
188     ₹ 39,265/sq.ft.
189      ₹ 6,083/sq.ft.
190    ₹ 230,547/sq.ft.
191      ₹ 8,411/sq.ft.
192     ₹ 32,291/sq.ft.
193     ₹ 41,666/sq.ft.
194      ₹ 8,889/sq.ft.
195      ₹ 7,280/sq.ft.
196     ₹ 90,000/sq.ft.
197     ₹ 10,089/sq.ft.
198      ₹ 8,697/sq.ft.
199      ₹ 8,500/sq.ft.
200      ₹ 9,333/sq.ft.
201      ₹ 8,235/sq.ft.
202     ₹ 13,333/sq.ft.
203     ₹ 21,667/sq.ft.
204     ₹ 20,425/sq.ft.
205      ₹ 5,472/sq.ft.
206      ₹ 6,944/sq.ft.
207     ₹ 57,692/sq.ft.
208     ₹ 60,000/sq.ft.
209      ₹ 3,857/sq.ft.
210     ₹ 21,759/sq.ft.
211      ₹ 8,333/sq.ft.
212      ₹ 7,407/sq.ft.
213     ₹ 75,000/sq.ft.
214     ₹ 10,482/sq.ft.
215     ₹ 25,386/sq.ft.
216      ₹ 8,735/sq.ft.
217      ₹ 9,444/sq.ft.
220     ₹ 20,000/sq.ft.
221     ₹ 18,667/sq.ft.
222     ₹ 18,889/sq.ft.
223      ₹ 2,525/sq.ft.
224     ₹ 24,306/sq.ft.
225     ₹ 17,695/sq.ft.
226     ₹ 21,519/sq.ft.
227     ₹ 17,817/sq.ft.
228          ₹ 2/sq.ft.
229      ₹ 6,173/sq.ft.
230     ₹ 55,000/sq.ft.
231     ₹ 13,888/sq.ft.
232     ₹ 20,323/sq.ft.
233     ₹ 20,359/sq.ft.
234      ₹ 5,833/sq.ft.
235     ₹ 11,693/sq.ft.
236     ₹ 26,667/sq.ft.
237     ₹ 53,125/sq.ft.
238     ₹ 17,900/sq.ft.
239     ₹ 39,886/sq.ft.
240    ₹ 126,865/sq.ft.
241     ₹ 40,909/sq.ft.
242     ₹ 27,155/sq.ft.
243     ₹ 14,492/sq.ft.
246     ₹ 14,167/sq.ft.
247     ₹ 11,111/sq.ft.
248     ₹ 13,157/sq.ft.
249      ₹ 5,888/sq.ft.
250     ₹ 11,111/sq.ft.
251      ₹ 7,875/sq.ft.
252      ₹ 9,654/sq.ft.
253      ₹ 4,808/sq.ft.
254      ₹ 8,222/sq.ft.
255     ₹ 11,111/sq.ft.
256      ₹ 3,857/sq.ft.
257     ₹ 50,000/sq.ft.
258     ₹ 11,273/sq.ft.
259      ₹ 8,000/sq.ft.
260      ₹ 7,627/sq.ft.
261      ₹ 5,666/sq.ft.
262      ₹ 5,000/sq.ft.
263      ₹ 5,000/sq.ft.
264      ₹ 6,567/sq.ft.
265     ₹ 22,068/sq.ft.
266      ₹ 8,386/sq.ft.
267     ₹ 12,444/sq.ft.
268     ₹ 11,111/sq.ft.
269     ₹ 28,674/sq.ft.
270      ₹ 9,725/sq.ft.
271     ₹ 21,111/sq.ft.
272      ₹ 7,500/sq.ft.
273     ₹ 10,784/sq.ft.
274     ₹ 12,162/sq.ft.
275      ₹ 8,910/sq.ft.
276     ₹ 10,518/sq.ft.
277     ₹ 19,869/sq.ft.
278      ₹ 8,796/sq.ft.
279      ₹ 9,722/sq.ft.
280      ₹ 7,522/sq.ft.
281      ₹ 5,658/sq.ft.
282      ₹ 5,000/sq.ft.
283     ₹ 24,545/sq.ft.
284      ₹ 7,701/sq.ft.
285      ₹ 8,235/sq.ft.
286     ₹ 14,072/sq.ft.
287     ₹ 26,000/sq.ft.
288     ₹ 24,305/sq.ft.
289     ₹ 19,286/sq.ft.
290     ₹ 22,634/sq.ft.
291     ₹ 26,570/sq.ft.
292     ₹ 11,111/sq.ft.
293      ₹ 6,410/sq.ft.
294    ₹ 133,079/sq.ft.
295     ₹ 15,257/sq.ft.
297      ₹ 5,778/sq.ft.
298      ₹ 6,111/sq.ft.
299     ₹ 15,625/sq.ft.
300     ₹ 78,125/sq.ft.
301     ₹ 17,955/sq.ft.
302      ₹ 7,916/sq.ft.
303    ₹ 211,111/sq.ft.
304     ₹ 80,000/sq.ft.
305     ₹ 35,000/sq.ft.
306     ₹ 10,000/sq.ft.
307    ₹ 120,000/sq.ft.
308     ₹ 22,297/sq.ft.
309    ₹ 125,000/sq.ft.
310      ₹ 8,889/sq.ft.
311     ₹ 73,333/sq.ft.
312     ₹ 11,111/sq.ft.
313     ₹ 26,235/sq.ft.
314      ₹ 6,790/sq.ft.
315     ₹ 20,833/sq.ft.
316    ₹ 315,789/sq.ft.
317     ₹ 10,224/sq.ft.
318      ₹ 3,500/sq.ft.
319      ₹ 3,285/sq.ft.
320     ₹ 74,000/sq.ft.
321     ₹ 27,139/sq.ft.
322     ₹ 10,000/sq.ft.
323      ₹ 5,555/sq.ft.
325     ₹ 23,662/sq.ft.
326     ₹ 17,574/sq.ft.
327     ₹ 13,333/sq.ft.
328     ₹ 10,753/sq.ft.
329      ₹ 9,091/sq.ft.
330     ₹ 23,557/sq.ft.
331     ₹ 59,259/sq.ft.
332    ₹ 105,263/sq.ft.
333     ₹ 21,195/sq.ft.
334        ₹ 151/sq.ft.
335     ₹ 25,103/sq.ft.
336     ₹ 13,889/sq.ft.
337     ₹ 14,954/sq.ft.
338     ₹ 23,333/sq.ft.
339      ₹ 8,784/sq.ft.
340      ₹ 6,500/sq.ft.
341     ₹ 35,494/sq.ft.
342     ₹ 11,464/sq.ft.
343     ₹ 11,718/sq.ft.
344     ₹ 11,555/sq.ft.
345     ₹ 50,000/sq.ft.
346      ₹ 3,874/sq.ft.
347      ₹ 7,576/sq.ft.
348     ₹ 11,556/sq.ft.
349     ₹ 10,753/sq.ft.
350     ₹ 20,635/sq.ft.
351     ₹ 10,378/sq.ft.
352     ₹ 11,888/sq.ft.
353     ₹ 17,284/sq.ft.
354     ₹ 32,258/sq.ft.
355     ₹ 11,111/sq.ft.
356     ₹ 12,222/sq.ft.
357     ₹ 16,389/sq.ft.
358     ₹ 31,506/sq.ft.
359      ₹ 9,722/sq.ft.
360     ₹ 12,820/sq.ft.
361    ₹ 229,885/sq.ft.
362     ₹ 10,000/sq.ft.
363      ₹ 8,889/sq.ft.
364     ₹ 12,400/sq.ft.
365      ₹ 9,259/sq.ft.
366        ₹ 232/sq.ft.
367     ₹ 15,257/sq.ft.
368    ₹ 218,750/sq.ft.
369     ₹ 54,794/sq.ft.
370     ₹ 14,245/sq.ft.
371      ₹ 6,367/sq.ft.
372     ₹ 37,313/sq.ft.
373     ₹ 90,909/sq.ft.
374      ₹ 9,444/sq.ft.
375      ₹ 5,000/sq.ft.
376     ₹ 10,122/sq.ft.
377     ₹ 10,000/sq.ft.
378      ₹ 8,642/sq.ft.
379      ₹ 6,481/sq.ft.
380      ₹ 6,707/sq.ft.
381    ₹ 245,398/sq.ft.
382      ₹ 9,259/sq.ft.
383     ₹ 11,904/sq.ft.
384      ₹ 9,135/sq.ft.
386      ₹ 7,111/sq.ft.
387      ₹ 8,012/sq.ft.
388    ₹ 183,333/sq.ft.
389     ₹ 12,500/sq.ft.
390     ₹ 10,142/sq.ft.
391      ₹ 8,444/sq.ft.
392      ₹ 8,125/sq.ft.
393     ₹ 14,583/sq.ft.
394     ₹ 17,037/sq.ft.
395     ₹ 11,538/sq.ft.
396      ₹ 8,730/sq.ft.
397     ₹ 12,222/sq.ft.
398     ₹ 14,444/sq.ft.
399     ₹ 11,574/sq.ft.
400     ₹ 26,667/sq.ft.
401     ₹ 11,111/sq.ft.
402      ₹ 8,230/sq.ft.
403     ₹ 13,095/sq.ft.
404     ₹ 30,556/sq.ft.
405     ₹ 11,852/sq.ft.
406     ₹ 10,000/sq.ft.
407     ₹ 29,311/sq.ft.
408     ₹ 11,250/sq.ft.
409     ₹ 30,384/sq.ft.
410      ₹ 8,444/sq.ft.
411     ₹ 19,818/sq.ft.
412      ₹ 1,992/sq.ft.
413      ₹ 7,619/sq.ft.
414     ₹ 98,214/sq.ft.
415     ₹ 13,499/sq.ft.
416      ₹ 7,820/sq.ft.
417      ₹ 5,555/sq.ft.
418      ₹ 4,000/sq.ft.
419     ₹ 14,720/sq.ft.
420      ₹ 5,664/sq.ft.
421     ₹ 19,753/sq.ft.
422     ₹ 76,000/sq.ft.
423     ₹ 37,037/sq.ft.
424     ₹ 63,492/sq.ft.
425      ₹ 9,000/sq.ft.
426      ₹ 4,444/sq.ft.
427      ₹ 2,500/sq.ft.
428      ₹ 6,667/sq.ft.
429      ₹ 3,704/sq.ft.
430     ₹ 12,777/sq.ft.
431      ₹ 6,648/sq.ft.
432     ₹ 11,407/sq.ft.
433     ₹ 20,233/sq.ft.
434     ₹ 17,778/sq.ft.
435     ₹ 20,062/sq.ft.
436     ₹ 11,494/sq.ft.
437     ₹ 25,543/sq.ft.
438     ₹ 12,343/sq.ft.
439     ₹ 16,892/sq.ft.
440      ₹ 8,000/sq.ft.
441     ₹ 17,500/sq.ft.
442      ₹ 3,904/sq.ft.
443     ₹ 14,323/sq.ft.
444      ₹ 4,222/sq.ft.
445    ₹ 181,818/sq.ft.
446     ₹ 75,000/sq.ft.
447     ₹ 26,620/sq.ft.
448      ₹ 5,555/sq.ft.
449     ₹ 10,000/sq.ft.
450      ₹ 9,722/sq.ft.
451      ₹ 9,500/sq.ft.
452     ₹ 17,937/sq.ft.
453      ₹ 3,254/sq.ft.
454      ₹ 5,333/sq.ft.
455     ₹ 30,556/sq.ft.
456      ₹ 4,583/sq.ft.
457     ₹ 12,500/sq.ft.
458     ₹ 21,875/sq.ft.
460     ₹ 16,667/sq.ft.
461      ₹ 7,075/sq.ft.
462      ₹ 8,078/sq.ft.
463      ₹ 4,251/sq.ft.
464     ₹ 17,584/sq.ft.
465      ₹ 5,397/sq.ft.
466      ₹ 9,074/sq.ft.
467      ₹ 5,583/sq.ft.
468      ₹ 3,519/sq.ft.
469     ₹ 11,194/sq.ft.
470    ₹ 100,000/sq.ft.
471      ₹ 6,981/sq.ft.
472      ₹ 6,702/sq.ft.
473      ₹ 9,444/sq.ft.
474     ₹ 10,556/sq.ft.
475     ₹ 18,333/sq.ft.
476      ₹ 4,877/sq.ft.
477      ₹ 7,479/sq.ft.
478      ₹ 7,400/sq.ft.
479     ₹ 16,003/sq.ft.
480      ₹ 8,000/sq.ft.
481      ₹ 9,444/sq.ft.
482      ₹ 9,103/sq.ft.
483      ₹ 7,727/sq.ft.
484     ₹ 45,710/sq.ft.
486      ₹ 8,702/sq.ft.
487      ₹ 5,950/sq.ft.
488      ₹ 3,500/sq.ft.
489      ₹ 9,722/sq.ft.
490      ₹ 8,889/sq.ft.
491     ₹ 26,973/sq.ft.
492     ₹ 32,407/sq.ft.
493     ₹ 13,750/sq.ft.
494      ₹ 6,000/sq.ft.
495     ₹ 14,890/sq.ft.
496      ₹ 9,210/sq.ft.
497      ₹ 6,800/sq.ft.
498     ₹ 10,518/sq.ft.
499      ₹ 7,333/sq.ft.
500      ₹ 8,101/sq.ft.
501      ₹ 6,944/sq.ft.
502     ₹ 14,184/sq.ft.
503      ₹ 4,260/sq.ft.
504     ₹ 10,582/sq.ft.
505      ₹ 9,390/sq.ft.
506     ₹ 84,000/sq.ft.
507      ₹ 6,938/sq.ft.
508     ₹ 15,555/sq.ft.
509     ₹ 33,333/sq.ft.
510      ₹ 7,539/sq.ft.
511     ₹ 10,000/sq.ft.
512     ₹ 10,067/sq.ft.
513      ₹ 1,649/sq.ft.
514     ₹ 10,000/sq.ft.
515     ₹ 10,000/sq.ft.
516     ₹ 13,000/sq.ft.
517     ₹ 28,898/sq.ft.
518     ₹ 28,200/sq.ft.
519      ₹ 7,168/sq.ft.
520     ₹ 20,444/sq.ft.
521     ₹ 35,185/sq.ft.
522      ₹ 6,289/sq.ft.
523     ₹ 17,857/sq.ft.
524      ₹ 7,000/sq.ft.
525     ₹ 14,166/sq.ft.
526     ₹ 30,968/sq.ft.
527      ₹ 7,777/sq.ft.
528     ₹ 18,658/sq.ft.
529     ₹ 10,484/sq.ft.
530    ₹ 160,000/sq.ft.
531      ₹ 8,127/sq.ft.
532      ₹ 5,000/sq.ft.
533      ₹ 8,000/sq.ft.
534      ₹ 7,555/sq.ft.
535     ₹ 49,500/sq.ft.
536      ₹ 8,889/sq.ft.
537     ₹ 13,030/sq.ft.
538    ₹ 308,333/sq.ft.
539      ₹ 8,333/sq.ft.
540     ₹ 10,610/sq.ft.
541     ₹ 18,889/sq.ft.
542      ₹ 7,302/sq.ft.
543      ₹ 8,155/sq.ft.
544     ₹ 10,591/sq.ft.
545     ₹ 24,074/sq.ft.
546     ₹ 14,815/sq.ft.
547      ₹ 5,160/sq.ft.
548    ₹ 144,444/sq.ft.
549      ₹ 9,615/sq.ft.
550      ₹ 9,444/sq.ft.
551     ₹ 10,101/sq.ft.
552     ₹ 22,222/sq.ft.
553     ₹ 32,407/sq.ft.
554      ₹ 6,813/sq.ft.
555     ₹ 15,046/sq.ft.
556     ₹ 11,583/sq.ft.
558      ₹ 6,034/sq.ft.
559     ₹ 10,085/sq.ft.
560     ₹ 17,778/sq.ft.
561     ₹ 40,611/sq.ft.
562     ₹ 29,630/sq.ft.
563     ₹ 29,629/sq.ft.
564     ₹ 10,740/sq.ft.
565      ₹ 4,444/sq.ft.
566     ₹ 17,980/sq.ft.
567     ₹ 55,000/sq.ft.
568     ₹ 19,737/sq.ft.
569      ₹ 5,093/sq.ft.
570     ₹ 25,463/sq.ft.
571     ₹ 12,000/sq.ft.
572      ₹ 7,007/sq.ft.
573      ₹ 8,920/sq.ft.
574     ₹ 35,294/sq.ft.
575     ₹ 12,963/sq.ft.
576      ₹ 8,254/sq.ft.
577      ₹ 5,128/sq.ft.
578      ₹ 5,777/sq.ft.
579     ₹ 15,926/sq.ft.
580     ₹ 11,111/sq.ft.
581     ₹ 14,285/sq.ft.
582     ₹ 34,307/sq.ft.
583     ₹ 51,864/sq.ft.
584     ₹ 44,265/sq.ft.
585     ₹ 29,444/sq.ft.
586     ₹ 39,074/sq.ft.
587     ₹ 38,734/sq.ft.
588     ₹ 23,442/sq.ft.
589     ₹ 41,833/sq.ft.
590     ₹ 27,778/sq.ft.
591    ₹ 600,000/sq.ft.
592     ₹ 23,889/sq.ft.
593     ₹ 25,000/sq.ft.
594     ₹ 10,260/sq.ft.
595     ₹ 31,915/sq.ft.
596     ₹ 11,102/sq.ft.
597      ₹ 8,866/sq.ft.
598     ₹ 36,911/sq.ft.
599     ₹ 36,111/sq.ft.
600     ₹ 15,444/sq.ft.
601     ₹ 11,240/sq.ft.
602     ₹ 15,437/sq.ft.
603     ₹ 14,351/sq.ft.
604     ₹ 27,191/sq.ft.
605    ₹ 241,666/sq.ft.
606     ₹ 32,963/sq.ft.
607     ₹ 33,592/sq.ft.
608     ₹ 24,455/sq.ft.
609     ₹ 26,667/sq.ft.
610     ₹ 26,389/sq.ft.
611    ₹ 194,444/sq.ft.
612     ₹ 18,444/sq.ft.
613     ₹ 11,600/sq.ft.
614     ₹ 38,095/sq.ft.
615     ₹ 13,492/sq.ft.
616     ₹ 33,951/sq.ft.
617     ₹ 11,157/sq.ft.
618      ₹ 8,444/sq.ft.
619     ₹ 21,495/sq.ft.
620     ₹ 42,054/sq.ft.
621      ₹ 1,560/sq.ft.
622     ₹ 20,741/sq.ft.
623     ₹ 13,178/sq.ft.
624     ₹ 12,000/sq.ft.
625     ₹ 26,428/sq.ft.
626     ₹ 82,540/sq.ft.
627     ₹ 18,888/sq.ft.
628     ₹ 31,481/sq.ft.
629     ₹ 13,501/sq.ft.
630     ₹ 20,988/sq.ft.
631    ₹ 400,000/sq.ft.
632     ₹ 21,296/sq.ft.
633     ₹ 34,722/sq.ft.
634     ₹ 18,626/sq.ft.
635     ₹ 24,366/sq.ft.
636     ₹ 26,298/sq.ft.
637      ₹ 7,500/sq.ft.
638     ₹ 24,171/sq.ft.
639     ₹ 23,000/sq.ft.
640     ₹ 29,697/sq.ft.
641     ₹ 33,333/sq.ft.
642     ₹ 36,111/sq.ft.
643      ₹ 6,778/sq.ft.
644     ₹ 22,812/sq.ft.
645    ₹ 261,194/sq.ft.
646    ₹ 178,571/sq.ft.
647     ₹ 27,461/sq.ft.
648     ₹ 31,686/sq.ft.
649     ₹ 22,222/sq.ft.
650     ₹ 23,061/sq.ft.
651     ₹ 32,222/sq.ft.
652     ₹ 17,662/sq.ft.
653     ₹ 39,841/sq.ft.
654     ₹ 37,627/sq.ft.
655     ₹ 23,148/sq.ft.
656     ₹ 29,880/sq.ft.
657     ₹ 20,068/sq.ft.
658     ₹ 16,569/sq.ft.
659     ₹ 21,242/sq.ft.
660     ₹ 11,574/sq.ft.
661     ₹ 32,562/sq.ft.
662     ₹ 13,000/sq.ft.
663     ₹ 22,429/sq.ft.
664     ₹ 39,530/sq.ft.
665     ₹ 22,222/sq.ft.
666     ₹ 38,889/sq.ft.
667     ₹ 57,206/sq.ft.
668     ₹ 27,222/sq.ft.
669     ₹ 63,554/sq.ft.
670     ₹ 10,601/sq.ft.
671     ₹ 20,940/sq.ft.
672     ₹ 32,253/sq.ft.
673     ₹ 37,037/sq.ft.
674     ₹ 23,704/sq.ft.
675     ₹ 23,693/sq.ft.
676     ₹ 15,989/sq.ft.
677     ₹ 19,268/sq.ft.
678     ₹ 19,360/sq.ft.
679     ₹ 45,833/sq.ft.
680     ₹ 29,880/sq.ft.
681     ₹ 23,437/sq.ft.
682      ₹ 2,716/sq.ft.
683     ₹ 39,841/sq.ft.
684     ₹ 32,222/sq.ft.
685     ₹ 40,850/sq.ft.
686     ₹ 12,342/sq.ft.
687     ₹ 15,555/sq.ft.
688     ₹ 26,111/sq.ft.
689     ₹ 31,790/sq.ft.
690     ₹ 24,691/sq.ft.
691    ₹ 235,376/sq.ft.
692     ₹ 29,293/sq.ft.
693     ₹ 16,004/sq.ft.
694     ₹ 27,333/sq.ft.
695     ₹ 17,624/sq.ft.
696     ₹ 38,580/sq.ft.
697     ₹ 27,778/sq.ft.
698     ₹ 35,556/sq.ft.
699     ₹ 38,580/sq.ft.
700     ₹ 35,000/sq.ft.
701     ₹ 30,864/sq.ft.
702    ₹ 161,849/sq.ft.
703     ₹ 27,778/sq.ft.
704     ₹ 16,056/sq.ft.
705     ₹ 17,707/sq.ft.
718      ₹ 7,718/sq.ft.
719     ₹ 25,535/sq.ft.
720      ₹ 1,859/sq.ft.
721     ₹ 17,037/sq.ft.
722     ₹ 10,579/sq.ft.
723     ₹ 42,194/sq.ft.
724     ₹ 15,625/sq.ft.
725     ₹ 15,278/sq.ft.
726    ₹ 201,388/sq.ft.
727     ₹ 17,187/sq.ft.
728     ₹ 44,444/sq.ft.
729     ₹ 18,928/sq.ft.
730     ₹ 10,926/sq.ft.
731     ₹ 19,608/sq.ft.
732      ₹ 8,089/sq.ft.
733      ₹ 6,849/sq.ft.
734     ₹ 24,691/sq.ft.
735     ₹ 19,607/sq.ft.
736     ₹ 40,000/sq.ft.
737     ₹ 34,846/sq.ft.
738     ₹ 31,444/sq.ft.
739     ₹ 26,235/sq.ft.
740     ₹ 22,222/sq.ft.
741     ₹ 23,457/sq.ft.
742     ₹ 27,083/sq.ft.
743     ₹ 43,210/sq.ft.
744     ₹ 31,926/sq.ft.
745     ₹ 38,611/sq.ft.
746     ₹ 27,911/sq.ft.
747     ₹ 29,022/sq.ft.
748     ₹ 12,837/sq.ft.
749     ₹ 12,198/sq.ft.
750     ₹ 35,741/sq.ft.
751     ₹ 16,666/sq.ft.
752     ₹ 35,556/sq.ft.
753      ₹ 9,634/sq.ft.
755     ₹ 31,481/sq.ft.
756      ₹ 7,827/sq.ft.
757     ₹ 38,760/sq.ft.
758     ₹ 23,556/sq.ft.
759     ₹ 10,035/sq.ft.
760     ₹ 28,841/sq.ft.
761     ₹ 26,615/sq.ft.
762     ₹ 24,155/sq.ft.
763     ₹ 14,815/sq.ft.
764     ₹ 22,222/sq.ft.
765     ₹ 62,222/sq.ft.
766      ₹ 6,597/sq.ft.
767      ₹ 7,870/sq.ft.
768     ₹ 26,852/sq.ft.
769     ₹ 28,233/sq.ft.
770     ₹ 15,111/sq.ft.
771     ₹ 34,722/sq.ft.
772     ₹ 19,820/sq.ft.
773      ₹ 1,087/sq.ft.
774     ₹ 31,481/sq.ft.
775     ₹ 26,235/sq.ft.
776     ₹ 36,883/sq.ft.
777     ₹ 37,037/sq.ft.
778     ₹ 27,871/sq.ft.
779     ₹ 35,109/sq.ft.
780     ₹ 17,692/sq.ft.
781     ₹ 38,022/sq.ft.
782     ₹ 33,333/sq.ft.
783     ₹ 25,309/sq.ft.
784     ₹ 16,990/sq.ft.
785     ₹ 14,222/sq.ft.
786     ₹ 22,222/sq.ft.
787     ₹ 16,388/sq.ft.
788     ₹ 22,075/sq.ft.
789     ₹ 11,666/sq.ft.
790     ₹ 47,167/sq.ft.
791      ₹ 7,937/sq.ft.
792     ₹ 20,197/sq.ft.
793     ₹ 20,635/sq.ft.
794     ₹ 34,037/sq.ft.
795     ₹ 10,123/sq.ft.
796     ₹ 28,858/sq.ft.
797     ₹ 28,549/sq.ft.
798     ₹ 15,555/sq.ft.
799     ₹ 13,513/sq.ft.
800     ₹ 20,769/sq.ft.
801     ₹ 34,568/sq.ft.
802     ₹ 21,097/sq.ft.
803     ₹ 33,951/sq.ft.
804     ₹ 24,306/sq.ft.
805     ₹ 25,556/sq.ft.
806     ₹ 36,111/sq.ft.
807      ₹ 7,756/sq.ft.
808     ₹ 21,825/sq.ft.
809     ₹ 12,342/sq.ft.
810     ₹ 16,577/sq.ft.
811     ₹ 17,706/sq.ft.
812     ₹ 29,074/sq.ft.
813     ₹ 29,880/sq.ft.
814     ₹ 42,222/sq.ft.
815     ₹ 38,194/sq.ft.
816     ₹ 21,605/sq.ft.
817     ₹ 38,194/sq.ft.
818     ₹ 37,778/sq.ft.
819     ₹ 31,111/sq.ft.
820     ₹ 17,213/sq.ft.
821     ₹ 18,620/sq.ft.
822     ₹ 17,014/sq.ft.
823      ₹ 7,750/sq.ft.
824      ₹ 7,172/sq.ft.
825     ₹ 29,638/sq.ft.
826     ₹ 33,333/sq.ft.
827      ₹ 8,137/sq.ft.
828      ₹ 7,582/sq.ft.
829     ₹ 48,148/sq.ft.
830     ₹ 18,605/sq.ft.
831     ₹ 16,066/sq.ft.
832     ₹ 55,556/sq.ft.
833     ₹ 38,986/sq.ft.
834     ₹ 24,510/sq.ft.
835     ₹ 11,428/sq.ft.
836     ₹ 22,184/sq.ft.
837     ₹ 30,247/sq.ft.
838     ₹ 20,370/sq.ft.
839     ₹ 31,666/sq.ft.
840     ₹ 18,889/sq.ft.
841    ₹ 283,333/sq.ft.
842     ₹ 31,481/sq.ft.
843     ₹ 42,222/sq.ft.
844     ₹ 59,259/sq.ft.
845     ₹ 45,833/sq.ft.
846     ₹ 18,008/sq.ft.
847     ₹ 26,235/sq.ft.
848     ₹ 33,333/sq.ft.
849     ₹ 12,285/sq.ft.
850     ₹ 19,293/sq.ft.
851     ₹ 20,599/sq.ft.
852    ₹ 173,992/sq.ft.
853     ₹ 21,367/sq.ft.
854     ₹ 20,299/sq.ft.
855     ₹ 41,818/sq.ft.

In [30]:
houses['price_per_sqft']=houses['price_per_sqft'].apply(lambda ppsf: str(ppsf).strip().replace(' ','').replace('₹','').replace(',','').replace('/sq.ft.','')).astype('int64')

In [31]:
houses.head(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,105751,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,38251,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5.00,43066,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3.00,53763,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [32]:
houses[['bedRoom','bathroom','balcony','additionalRoom']].isna().sum()

bedRoom             0
bathroom            0
balcony             0
additionalRoom    379
dtype: int64

In [33]:
houses.bedRoom.value_counts()

bedRoom
4 Bedrooms     230
5 Bedrooms     183
3 Bedrooms     146
2 Bedrooms      87
6 Bedrooms      80
9 Bedrooms      44
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      30
12 Bedrooms     27
10 Bedrooms     21
16 Bedrooms     11
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [34]:
houses['bedRoom']=houses['bedRoom'].str.split().str.get(0).astype('int64')

In [35]:
houses['bathroom']=houses['bathroom'].str.split().str.get(0).astype('int64')

In [36]:
houses['balcony'].str.split().str.get(0).value_counts()

balcony
3+    352
2     217
3     158
No    114
1     104
Name: count, dtype: int64

In [37]:
houses['balcony']=houses['balcony'].str.replace('No','0').str.split().str.get(0)

In [38]:
houses['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     80
Pooja Room,Study Room,Servant Room,Store Room    59
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               32
Store Room                                       31
Pooja Room,Study Room,Servant Room,Others        29
Pooja Room,Servant Room                          24
Study Room                                       18
Study Room,Servant Room                          18
Servant Room,Store Room                          12
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Servant Room,Store Room                7
Pooja Room,Store Room,Study Room,Servant Room     7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [39]:
houses['additionalRoom'].value_counts().shape

(56,)

In [40]:
houses['additionalRoom'].isna().sum()

379

In [41]:
def handle(x):
  if x[0] == '0':
    return 0
  else  :
    return len(x)

In [42]:
houses['additionalRoom']=houses['additionalRoom'].fillna('0').str.split(',').apply(handle)

In [43]:
houses['additionalRoom']

0      1
1      3
2      1
3      1
4      1
5      1
6      3
7      1
8      1
9      1
10     1
11     4
12     1
13     4
14     4
15     2
16     3
17     3
18     2
19     4
20     0
21     2
22     2
23     3
24     3
25     3
26     3
27     1
28     2
29     1
30     3
31     2
32     1
33     1
34     0
35     1
36     4
37     1
38     1
39     4
40     4
41     1
42     3
43     4
44     1
45     2
46     2
47     4
48     3
49     0
50     4
51     4
52     3
53     1
54     4
55     3
56     0
57     4
58     4
59     1
60     1
61     0
62     2
63     1
64     0
65     1
66     2
67     3
68     0
69     0
70     3
71     4
72     2
73     2
74     1
75     4
76     0
77     3
78     4
79     3
80     0
81     0
82     0
83     0
84     0
85     1
86     4
87     2
88     4
89     1
90     3
91     1
92     1
93     1
94     1
95     1
96     1
97     1
98     4
99     2
100    0
101    2
102    2
103    1
104    1
105    2
106    1
107    1
108    1
109    2
110    1
111    1
112    1
113    0
114    3
115    1
116    1
117    1
118    1
119    1
120    4
121    3
122    4
123    2
124    2
125    1
126    1
127    0
128    0
129    3
130    0
131    0
132    1
133    1
134    4
135    4
136    0
137    0
138    2
139    1
140    1
141    1
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    2
150    0
151    3
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    0
161    0
162    0
163    4
164    2
165    0
166    0
167    0
168    0
169    0
170    0
171    0
172    1
173    0
174    4
175    0
176    0
177    0
178    0
179    0
180    0
181    1
182    1
183    0
184    2
185    0
186    0
187    4
188    1
189    0
190    0
191    0
192    0
193    0
194    0
195    0
196    0
197    0
198    0
199    0
200    0
201    1
202    1
203    0
204    0
205    0
206    1
207    0
208    0
209    0
210    2
211    1
212    0
213    0
214    0
215    1
216    0
217    0
220    0
221    0
222    0
223    0
224    0
225    0
226    0
227    0
228    0
229    0
230    0
231    1
232    0
233    0
234    0
235    1
236    0
237    0
238    0
239    1
240    1
241    0
242    0
243    0
246    0
247    0
248    0
249    0
250    0
251    1
252    3
253    0
254    1
255    1
256    0
257    0
258    0
259    0
260    0
261    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
271    0
272    0
273    0
274    0
275    0
276    2
277    0
278    1
279    0
280    0
281    1
282    0
283    0
284    0
285    0
286    0
287    0
288    0
289    0
290    1
291    0
292    1
293    0
294    3
295    0
297    0
298    0
299    0
300    0
301    0
302    0
303    0
304    4
305    0
306    0
307    1
308    0
309    0
310    0
311    1
312    0
313    3
314    2
315    0
316    0
317    0
318    0
319    0
320    0
321    2
322    1
323    1
325    2
326    0
327    2
328    0
329    0
330    1
331    0
332    1
333    0
334    1
335    1
336    0
337    0
338    1
339    2
340    0
341    0
342    4
343    0
344    0
345    3
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    0
354    0
355    0
356    0
357    2
358    1
359    0
360    4
361    0
362    0
363    0
364    1
365    0
366    4
367    1
368    0
369    0
370    2
371    0
372    1
373    0
374    1
375    1
376    0
377    0
378    0
379    0
380    0
381    0
382    0
383    0
384    0
386    0
387    1
388    3
389    0
390    0
391    0
392    0
393    0
394    3
395    0
396    0
397    0
398    2
399    1
400    0
401    4
402    1
403    2
404    2
405    0
406    0
407    1
408    0
409    0
410    0
411    1
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    2
420    0
421    0
422    0
423    0
424    0
425    0
426    0
427    0
428    0
429    0
430    0
431    0
432    0
433    0
434    0
435    0
436    0
437    0
438    0
439    0
440    0
441    0
442    0
443    0
444    0
445    2
446    0
447    0
448    0
449    1
450    0
451    1
452    0
453    0
454    0
455    0
456    0
457    0
458    0
460    0
461    0
462    0
463    2
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    4
486    0
487    0
488    0
489    2
490    3
491    0
492    0
493    0
494    0
495    3
496    0
497    0
498    0
499    0
500    0
501    0
502    1
503    0
504    0
505    0
506    0
507    0
508    0
509    0
510    0
511    1
512    0
513    0
514    2
515    0
516    0
517    4
518    1
519    0
520    0
521    0
522    0
523    1
524    0
525    0
526    1
527    0
528    0
529    0
530    0
531    0
532    0
533    2
534    0
535    0
536    1
537    0
538    0
539    0
540    0
541    0
542    0
543    0
544    0
545    3
546    0
547    2
548    0
549    2
550    0
551    2
552    0
553    0
554    0
555    0
556    1
558    0
559    1
560    1
561    3
562    0
563    0
564    0
565    0
566    2
567    0
568    3
569    4
570    1
571    0
572    2
573    0
574    0
575    0
576    1
577    0
578    1
579    2
580    0
581    1
582    4
583    4
584    4
585    4
586    4
587    4
588    2
589    4
590    3
591    3
592    3
593    0
594    2
595    1
596    0
597    2
598    2
599    4
600    4
601    1
602    1
603    4
604    3
605    1
606    4
607    4
608    1
609    1
610    4
611    1
612    0
613    1
614    2
615    4
616    3
617    1
618    2
619    2
620    2
621    2
622    1
623    0
624    2
625    0
626    4
627    1
628    0
629    4
630    1
631    2
632    3
633    2
634    1
635    4
636    4
637    1
638    4
639    4
640    4
641    2
642    2
643    1
644    4
645    2
646    1
647    2
648    3
649    3
650    2
651    1
652    2
653    3
654    3
655    3
656    4
657    2
658    1
659    3
660    1
661    2
662    0
663    4
664    3
665    1
666    2
667    4
668    4
669    1
670    1
671    4
672    4
673    4
674    2
675    2
676    0
677    0
678    0
679    1
680    3
681    3
682    4
683    4
684    1
685    2
686    4
687    4
688    4
689    4
690    4
691    2
692    1
693    1
694    3
695    4
696    2
697    4
698    0
699    4
700    4
701    4
702    1
703    0
704    0
705    2
718    2
719    1
720    3
721    4
722    4
723    3
724    4
725    4
726    4
727    0
728    2
729    1
730    1
731    1
732    1
733    1
734    3
735    3
736    4
737    2
738    2
739    0
740    1
741    1
742    3
743    2
744    0
745    2
746    1
747    3
748    0
749    0
750    1
751    1
752    3
753    4
755    2
756    3
757    4
758    4
759    4
760    4
761    1
762    1
763    0
764    2
765    2
766    1
767    2
768    3
769    4
770    0
771    3
772    4
773    1
774    1
775    2
776    2
777    2
778    3
779    4
780    3
781    1
782    2
783    3
784    0
785    0
786    4
787    1
788    4
789    1
790    2
791    2
792    3
793    3
794    2
795    2
796    2
797    4
798    1
799    2
800    2
801    3
802    4
803    4
804    4
805    4
806    4
807    4
808    3
809    1
810    4
811    2
812    4
813    4
814    4
815    1
816    1
817    2
818    3
819    4
820    1
821    0
822    0
823    1
824    1
825    3
826    1
827    1
828    2
829    1
830    4
831    2
832    3
833    4
834    1
835    4
836    1
837    1
838    1
839    3
840    3
841    1
842    2
843    2
844    4
845    2
846    1
847    2
848    2
849    0
850    4
851    4
852    0
853    0
854    1
855    0
856    0
857    4
858    4
859    4
860    1
861    0
862    2
863    1
864    4
865    1
866    3
867    2
868    2
869    3
870    1
871    4
872    3
873    1
874    1
875    1
876    1
877    2
878    4
879    4
880    1
881    3
882    4
883    3
884    1
885    2
886    4
887    1
888    0
889    1
890    2
891    1
892    1
893    1
894    1
895    1
896    4
897    1
898    1
899    3
900    1
901    1
902    1
903    3
904    2
905    3
906    2
907    1
908    2
909    3
910    4
911    1
912    1
913    3
914    4
915    3
916    3
917    4
918    3
919    1
920    3
921    3
922    3
923    2
924    2
925    4
926    1
927    4
928    1
929    0
930    2
931    1
932    1
933    1
934    1
935    3
936    1
937    1
938    1
939    1
940    4
941    2
942    2
943    1
944    0
945    2
946    0
947    1
948    1
949    2
950    2
951    1
952    1
953    1
954    1
955    1
956    1
957    1
958    1
959    1
960    2
961    1
962    4
963    3
964    1
965    2
966    1
967    4
Name: additionalRoom, dtype: int64

In [44]:
houses['additionalRoom'].value_counts()

additionalRoom
0    379
1    225
4    128
2    124
3     89
Name: count, dtype: int64

In [45]:
# houses[houses['balcony']=='3+'].sort_values(['bedRoom'])[['bedRoom','balcony']]

In [46]:
houses['floorNum']

0       3 Floors
1       2 Floors
2       5 Floors
3       5 Floors
4       5 Floors
5       4 Floors
6       3 Floors
7       4 Floors
8       3 Floors
9       4 Floors
10      2 Floors
11      3 Floors
12      4 Floors
13      3 Floors
14      3 Floors
15      3 Floors
16      3 Floors
17      3 Floors
18      3 Floors
19      3 Floors
20      3 Floors
21      3 Floors
22      2 Floors
23           NaN
24      4 Floors
25      3 Floors
26      1 Floors
27      3 Floors
28      3 Floors
29      3 Floors
30      2 Floors
31      3 Floors
32      3 Floors
33      1 Floors
34      2 Floors
35      3 Floors
36      4 Floors
37      1 Floors
38      3 Floors
39      3 Floors
40      2 Floors
41      1 Floors
42      4 Floors
43      4 Floors
44      4 Floors
45      4 Floors
46      2 Floors
47      3 Floors
48      2 Floors
49      2 Floors
50           NaN
51      3 Floors
52      2 Floors
53      3 Floors
54      2 Floors
55      2 Floors
56      2 Floors
57      3 Floors
58      3 Floors
59      3 Floors
60      3 Floors
61      1 Floors
62      3 Floors
63      4 Floors
64      2 Floors
65      2 Floors
66      2 Floors
67      3 Floors
68      2 Floors
69      1 Floors
70      3 Floors
71      2 Floors
72      2 Floors
73      1 Floors
74      3 Floors
75      3 Floors
76      1 Floors
77      4 Floors
78      2 Floors
79      1 Floors
80      1 Floors
81      3 Floors
82      2 Floors
83      2 Floors
84      2 Floors
85      3 Floors
86      2 Floors
87      3 Floors
88      3 Floors
89      2 Floors
90      3 Floors
91      2 Floors
92      2 Floors
93      3 Floors
94      2 Floors
95      2 Floors
96      2 Floors
97      2 Floors
98      3 Floors
99      2 Floors
100     2 Floors
101     2 Floors
102     1 Floors
103     2 Floors
104     1 Floors
105     2 Floors
106     1 Floors
107     2 Floors
108     2 Floors
109     2 Floors
110     2 Floors
111     3 Floors
112     4 Floors
113     4 Floors
114     2 Floors
115     4 Floors
116     1 Floors
117     2 Floors
118     2 Floors
119     2 Floors
120     4 Floors
121     4 Floors
122     3 Floors
123     4 Floors
124     3 Floors
125     3 Floors
126     2 Floors
127          NaN
128     1 Floors
129     3 Floors
130     1 Floors
131     1 Floors
132     4 Floors
133     2 Floors
134     3 Floors
135     4 Floors
136     2 Floors
137     1 Floors
138     3 Floors
139     3 Floors
140     3 Floors
141     2 Floors
142     1 Floors
143     3 Floors
144    02 Floors
145     3 Floors
146     2 Floors
147     2 Floors
148     2 Floors
149     1 Floors
150     1 Floors
151     1 Floors
152     2 Floors
153     2 Floors
154     2 Floors
155     1 Floors
156     1 Floors
157     1 Floors
158     3 Floors
159     1 Floors
160     1 Floors
161     3 Floors
162     3 Floors
163     1 Floors
164     3 Floors
165    14 Floors
166    21 Floors
167     1 Floors
168     1 Floors
169     2 Floors
170     3 Floors
171     1 Floors
172     1 Floors
173     1 Floors
174     2 Floors
175     0 Floors
176          NaN
177     3 Floors
178     3 Floors
179     3 Floors
180     1 Floors
181     2 Floors
182     3 Floors
183     3 Floors
184     2 Floors
185     1 Floors
186     3 Floors
187     2 Floors
188     3 Floors
189     1 Floors
190     1 Floors
191     1 Floors
192     3 Floors
193     3 Floors
194          NaN
195     3 Floors
196     1 Floors
197     3 Floors
198    12 Floors
199     1 Floors
200     2 Floors
201     2 Floors
202     2 Floors
203     1 Floors
204     3 Floors
205          NaN
206     3 Floors
207     1 Floors
208     3 Floors
209     3 Floors
210     2 Floors
211     0 Floors
212     1 Floors
213     1 Floors
214     1 Floors
215     0 Floors
216     3 Floors
217     1 Floors
220     2 Floors
221     2 Floors
222     1 Floors
223     1 Floors
224     1 Floors
225     2 Floors
226    27 Floors
227     4 Floors
228     3 Floors
229     3 Floors
230     2 Floors
231     1 Floors
232     1 Floors
233     1 Floors
234     1 Floors
235     3 Floors
236     3 Floors
237     4 Floors
238     4 Floors
239     4 Floors
240     1 Floors
241     3 Floors
242     2 Floors
243     3 Floors
246     4 Floors
247     2 Floors
248     2 Floors
249     1 Floors
250     2 Floors
251     2 Floors
252     4 Floors
253     1 Floors
254     1 Floors
255     2 Floors
256     3 Floors
257     1 Floors
258     2 Floors
259     3 Floors
260    13 Floors
261     1 Floors
262     1 Floors
263     1 Floors
264     1 Floors
265     3 Floors
266     2 Floors
267     4 Floors
268          NaN
269     3 Floors
270     3 Floors
271     3 Floors
272     6 Floors
273     2 Floors
274     4 Floors
275     1 Floors
276     3 Floors
277     1 Floors
278     1 Floors
279     1 Floors
280     1 Floors
281     2 Floors
282     1 Floors
283     3 Floors
284     1 Floors
285     3 Floors
286     1 Floors
287     4 Floors
288     3 Floors
289     1 Floors
290     3 Floors
291          NaN
292     2 Floors
293     2 Floors
294     3 Floors
295     1 Floors
297     2 Floors
298     2 Floors
299     1 Floors
300     1 Floors
301     1 Floors
302     1 Floors
303     1 Floors
304     3 Floors
305     3 Floors
306     1 Floors
307     3 Floors
308     4 Floors
309     4 Floors
310     2 Floors
311          NaN
312     1 Floors
313     3 Floors
314     2 Floors
315     4 Floors
316     2 Floors
317     2 Floors
318     1 Floors
319     1 Floors
320     1 Floors
321     3 Floors
322     3 Floors
323     1 Floors
325     4 Floors
326     1 Floors
327     4 Floors
328     2 Floors
329     2 Floors
330     3 Floors
331     6 Floors
332     2 Floors
333     2 Floors
334     3 Floors
335     2 Floors
336     3 Floors
337     3 Floors
338     4 Floors
339     1 Floors
340     1 Floors
341     1 Floors
342     3 Floors
343     2 Floors
344     2 Floors
345     1 Floors
346     1 Floors
347     1 Floors
348     1 Floors
349     1 Floors
350     2 Floors
351     1 Floors
352     1 Floors
353     3 Floors
354     2 Floors
355     2 Floors
356     1 Floors
357     3 Floors
358     3 Floors
359     2 Floors
360     3 Floors
361     1 Floors
362     1 Floors
363     1 Floors
364     2 Floors
365     3 Floors
366     2 Floors
367     4 Floors
368     3 Floors
369     3 Floors
370     1 Floors
371    10 Floors
372     4 Floors
373     4 Floors
374     1 Floors
375     2 Floors
376     2 Floors
377     1 Floors
378     2 Floors
379     1 Floors
380     2 Floors
381     5 Floors
382     1 Floors
383     3 Floors
384     2 Floors
386     1 Floors
387     1 Floors
388     3 Floors
389     3 Floors
390     2 Floors
391     1 Floors
392    20 Floors
393     3 Floors
394     3 Floors
395     4 Floors
396     3 Floors
397     3 Floors
398     3 Floors
399     2 Floors
400     1 Floors
401     2 Floors
402     3 Floors
403     3 Floors
404     2 Floors
405     2 Floors
406     4 Floors
407     2 Floors
408     3 Floors
409     3 Floors
410     1 Floors
411     4 Floors
412     1 Floors
413     1 Floors
414     2 Floors
415     3 Floors
416     1 Floors
417     1 Floors
418     1 Floors
419     1 Floors
420     1 Floors
421     2 Floors
422     1 Floors
423     3 Floors
424     1 Floors
425     3 Floors
426     3 Floors
427     1 Floors
428     1 Floors
429     2 Floors
430     4 Floors
431     1 Floors
432     1 Floors
433     1 Floors
434     4 Floors
435     2 Floors
436     3 Floors
437     4 Floors
438     2 Floors
439     2 Floors
440     1 Floors
441     2 Floors
442     1 Floors
443     1 Floors
444     3 Floors
445     4 Floors
446     3 Floors
447     4 Floors
448     1 Floors
449     4 Floors
450          NaN
451     2 Floors
452     2 Floors
453     0 Floors
454     2 Floors
455     3 Floors
456     2 Floors
457     3 Floors
458     3 Floors
460     3 Floors
461     3 Floors
462     1 Floors
463     1 Floors
464     3 Floors
465    14 Floors
466     1 Floors
467     3 Floors
468     3 Floors
469     3 Floors
470     4 Floors
471    14 Floors
472    12 Floors
473     1 Floors
474     4 Floors
475     3 Floors
476     4 Floors
477     1 Floors
478     2 Floors
479     3 Floors
480     1 Floors
481     1 Floors
482     2 Floors
483     4 Floors
484          NaN
486     2 Floors
487     3 Floors
488     2 Floors
489     3 Floors
490     2 Floors
491     1 Floors
492     1 Floors
493     1 Floors
494     1 Floors
495     3 Floors
496     1 Floors
497     1 Floors
498     3 Floors
499     1 Floors
500     2 Floors
501     1 Floors
502     2 Floors
503     3 Floors
504     3 Floors
505     3 Floors
506     3 Floors
507     1 Floors
508     1 Floors
509     2 Floors
510     1 Floors
511     3 Floors
512    11 Floors
513     0 Floors
514     3 Floors
515     4 Floors
516     3 Floors
517     3 Floors
518     3 Floors
519     4 Floors
520     1 Floors
521     3 Floors
522     1 Floors
523     1 Floors
524     5 Floors
525     4 Floors
526    11 Floors
527     1 Floors
528     2 Floors
529     1 Floors
530    41 Floors
531     1 Floors
532     1 Floors
533     3 Floors
534     1 Floors
535     3 Floors
536     4 Floors
537     1 Floors
538     5 Floors
539     2 Floors
540     2 Floors
541     3 Floors
542     3 Floors
543     2 Floors
544     2 Floors
545     4 Floors
546     3 Floors
547     5 Floors
548     3 Floors
549     1 Floors
550     1 Floors
551     3 Floors
552     2 Floors
553     3 Floors
554     1 Floors
555          NaN
556     3 Floors
558     1 Floors
559     2 Floors
560     3 Floors
561     4 Floors
562     4 Floors
563     4 Floors
564     2 Floors
565     2 Floors
566     3 Floors
567     1 Floors
568     2 Floors
569     2 Floors
570     2 Floors
571     2 Floors
572     1 Floors
573     3 Floors
574     4 Floors
575     2 Floors
576     1 Floors
577     2 Floors
578     1 Floors
579     1 Floors
580     3 Floors
581     4 Floors
582     3 Floors
583     4 Floors
584     4 Floors
585     3 Floors
586     3 Floors
587     3 Floors
588     3 Floors
589     3 Floors
590     3 Floors
591     1 Floors
592     3 Floors
593     3 Floors
594     2 Floors
595     3 Floors
596     3 Floors
597     4 Floors
598          NaN
599     3 Floors
600     2 Floors
601     2 Floors
602     4 Floors
603     1 Floors
604     3 Floors
605     4 Floors
606     2 Floors
607     3 Floors
608     3 Floors
609     3 Floors
610     2 Floors
611     3 Floors
612     2 Floors
613     2 Floors
614     4 Floors
615    10 Floors
616     3 Floors
617     4 Floors
618     2 Floors
619     4 Floors
620     2 Floors
621     3 Floors
622     3 Floors
623     3 Floors
624     2 Floors
625     1 Floors
626     4 Floors
627     2 Floors
628     4 Floors
629     2 Floors
630     3 Floors
631     4 Floors
632     2 Floors
633     2 Floors
634     2 Floors
635     3 Floors
636     4 Floors
637     5 Floors
638     4 Floors
639     4 Floors
640     3 Floors
641     3 Floors
642     3 Floors
643     4 Floors
644     2 Floors
645     2 Floors
646     2 Floors
647     4 Floors
648     4 Floors
649    51 Floors
650     3 Floors
651     3 Floors
652     2 Floors
653     3 Floors
654     2 Floors
655     2 Floors
656     2 Floors
657     3 Floors
658     1 Floors
659     3 Floors
660     2 Floors
661     2 Floors
662     4 Floors
663     3 Floors
664     4 Floors
665     3 Floors
666     2 Floors
667     2 Floors
668     3 Floors
669     1 Floors
670     2 Floors
671     1 Floors
672     3 Floors
673     3 Floors
674     3 Floors
675     3 Floors
676     2 Floors
677     3 Floors
678     2 Floors
679     4 Floors
680     2 Floors
681     2 Floors
682     3 Floors
683     4 Floors
684     2 Floors
685     2 Floors
686     4 Floors
687     3 Floors
688     2 Floors
689     3 Floors
690     2 Floors
691     2 Floors
692     4 Floors
693     2 Floors
694     3 Floors
695     3 Floors
696     2 Floors
697     2 Floors
698     2 Floors
699     2 Floors
700     3 Floors
701     4 Floors
702     2 Floors
703     2 Floors
704     4 Floors
705     3 Floors
718          NaN
719     4 Floors
720     4 Floors
721     3 Floors
722     3 Floors
723     4 Floors
724     3 Floors
725     3 Floors
726     2 Floors
727     4 Floors
728     3 Floors
729     4 Floors
730     4 Floors
731     3 Floors
732     4 Floors
733     4 Floors
734     3 Floors
735     1 Floors
736     3 Floors
737     2 Floors
738     4 Floors
739          NaN
740     2 Floors
741     2 Floors
742     2 Floors
743     4 Floors
744     3 Floors
745     4 Floors
746          NaN
747     3 Floors
748     4 Floors
749          NaN
750     2 Floors
751     2 Floors
752     3 Floors
753     2 Floors
755     3 Floors
756     4 Floors
757     4 Floors
758     3 Floors
759     3 Floors
760     3 Floors
761     3 Floors
762     2 Floors
763     2 Floors
764     2 Floors
765     2 Floors
766    16 Floors
767     4 Floors
768     2 Floors
769     3 Floors
770     1 Floors
771     2 Floors
772     2 Floors
773     3 Floors
774     3 Floors
775     1 Floors
776     1 Floors
777     1 Floors
778     2 Floors
779     3 Floors
780     3 Floors
781     4 Floors
782     3 Floors
783     2 Floors
784     4 Floors
785     2 Floors
786     3 Floors
787     2 Floors
788     2 Floors
789     4 Floors
790     4 Floors
791     2 Floors
792     3 Floors
793     2 Floors
794     4 Floors
795     4 Floors
796     4 Floors
797     4 Floors
798     2 Floors
799     2 Floors
800     2 Floors
801     2 Floors
802     3 Floors
803     2 Floors
804     3 Floors
805     2 Floors
806     2 Floors
807     3 Floors
808     3 Floors
809     4 Floors
810     4 Floors
811     2 Floors
812     3 Floors
813     2 Floors
814     3 Floors
815     4 Floors
816     3 Floors
817     3 Floors
818     1 Floors
819     2 Floors
820     3 Floors
821     3 Floors
822     2 Floors
823     3 Floors
824     2 Floors
825     3 Floors
826     4 Floors
827     2 Floors
828     3 Floors
829     4 Floors
830     3 Floors
831     3 Floors
832     3 Floors
833     4 Floors
834     3 Floors
835     2 Floors
836     2 Floors
837     2 Floors
838     3 Floors
839     3 Floors
840     3 Floors
841     1 Floors
842     3 Floors
843     2 Floors
844     4 Floors
845     4 Floors
846     3 Floors
847     3 Floors
848     4 Floors
849     3 Floors
850     2 Floors
851     2 Floors
852     3 Floors
853     2 Floors
854     2 Floors
855     2 Floors
856     2 Floors
857     2 Floors
858     2 Floors
859     3 Floors
860     6 Floors
861     1 Floors
862     2 Floors
863     2 Floors
864     4 Floors
865     3 Floors
866     3 Floors
867     2 Floors
868     2 Floors
869     4 Floors
870     3 Floors
871     2 Floors
872     2 Floors
873     2 Floors
874     2 Floors
875     2 Floors
876     3 Floors
877     4 Floors
878     4 Floors
879     3 Floors
880     3 Floors
881     3 Floors
882     2 Floors
883          NaN
884     4 Floors
885     3 Floors
886     2 Floors
887     2 Floors
888     2 Floors
889     2 Floors
890     2 Floors
891     2 Floors
892     2 Floors
893     2 Floors
894     2 Floors
895     3 Floors
896          NaN
897     3 Floors
898     2 Floors
899     1 Floors
900     3 Floors
901     2 Floors
902     3 Floors
903     1 Floors
904     2 Floors
905     2 Floors
906     2 Floors
907     2 Floors
908     3 Floors
909     2 Floors
910     3 Floors
911     3 Floors
912     2 Floors
913     3 Floors
914    33 Floors
915     3 Floors
916     2 Floors
917     3 Floors
918     3 Floors
919     2 Floors
920     3 Floors
921     2 Floors
922     2 Floors
923     2 Floors
924     2 Floors
925     2 Floors
926     1 Floors
927     3 Floors
928     3 Floors
929     3 Floors
930     4 Floors
931     0 Floors
932     4 Floors
933     4 Floors
934     2 Floors
935     2 Floors
936     3 Floors
937     3 Floors
938     2 Floors
939     4 Floors
940     4 Floors
941     3 Floors
942     3 Floors
943     3 Floors
944     2 Floors
945     4 Floors
946     3 Floors
947     4 Floors
948     5 Floors
949     3 Floors
950     2 Floors
951     3 Floors
952     2 Floors
953     3 Floors
954     3 Floors
955     3 Floors
956     2 Floors
957     3 Floors
958     3 Floors
959     3 Floors
960     2 Floors
961     2 Floors
962     2 Floors
963     2 Floors
964     2 Floors
965     2 Floors
966     2 Floors
967     2 Floors
Name: floorNum, dtype: object

In [47]:
houses['floorNum'].str.split().str.get(0).value_counts()

floorNum
3     299
2     282
1     179
4     130
5       9
0       6
14      3
6       3
11      2
12      2
10      2
16      1
51      1
41      1
27      1
20      1
13      1
21      1
02      1
33      1
Name: count, dtype: int64

In [48]:
houses['floorNum']=houses['floorNum'].str.split().str.get(0).astype('float64')

In [49]:
houses[houses['floorNum'].isna()] # info available in address

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
23,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,2,3,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
50,8 Bedroom House for sale in Palam Vihar,nan,5.60,17284,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8,6,3+,4,"Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
127,3 Bedroom House for sale in DLF Phase 3,nan,1.45,26852,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),3,3,1,0,"DLF Phase 3, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.Pla...,NaN,['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
176,3 Bedroom House for sale in Ashok Vihar,nan,1.50,10288,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,0,0,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",NaN,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
194,2 Bedroom House for sale in Laxman Vihar Phase 2,nan,4.12,8889,(431 sq.m.) Plot Area,Plot area 515(430.61 sq.m.),2,1,3+,0,"Laxman Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...","Property next to dhanwapur underpass, which is...",[],NaN,NaN
205,3 Bedroom House for sale in New Palam Vihar Ph...,nan,2.50,5472,(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),3,2,1,0,"B-245, New Palam Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",100 mtr from dwarka express way. On 40ft road,NaN,['Park'],NaN
268,4 Bedroom House for sale in Laxman Vihar,nan,0.65,11111,(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.),4,2,2,0,"Laxman Vihar, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Well maintained two storeyed independent house...,"['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
291,1 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,3.30,26570,(115 sq.m.) Plot Area,Plot area 138(115.39 sq.m.),1,1,0,0,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,NaN,By 2027,"['Iffco chowk metro station', 'Huda city centr...","Close proximity to gold souk , huda city centr...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
311,2 Bedroom House for sale in Bhawani Enclave,nan,1.10,73333,(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1,1,"Bhawani Enclave, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
450,2 Bedroom House for sale in Jacobpura,jacob pura,0.35,9722,(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),2,1,0,0,"15/3, Jacobpura, Jacobpura, Gurgaon, Haryana",NaN,NaN,10+ Year Old,NaN,Independece house for sale in jacobpura near k...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
484,6 Bedroom House for sale in DLF Phase 2,nan,13.00,45710,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,8,3+,4,"DLF Phase 2, Gurgaon, Haryana",NaN,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
555,3 Bedroom House for sale in New Colony,nan,6.50,15046,(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3,2,3+,0,"New Colony, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
598,12 Bedroom House for sale in Sector 46 Gurgaon,nan,6.81,36911,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),12,14,3+,2,"Sector 46 Gurgaon, Gurgaon, Haryana",NaN,East,0 to 1 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 sqyds newly floor wise building with basem...,"['14 Wardrobe', '15 Fan', '1 Exhaust Fan', '13...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
718,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,2.47,7718,(297 sq.m.) Plot Area,Plot area 3200(297.29 sq.m.)Built Up area: 280...,4,4,3+,2,"Sector 86 Gurgaon, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",This is beautiful 4 bhk villa in dlf new town ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
739,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,1,0,"4 Bed And 4 Bathroom, Sector 48 Gurgaon, Gurga...",NaN,NaN,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",360 sq yard 4 bhk residential villa for sale i...,"['4 Bed', '4 Fan', '1 Exhaust Fan', '4 Light',...","['Maintenance Staff', 'Water Storage', 'Separa...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
746,4 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok,10.50,27911,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),4,4,2,1,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...",Ansal villa for sale 418 sqyd in d block gated...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
749,4 Bedroom House for sale in Sector 26 Gurgaon,nan,4.60,12198,(350 sq.m.) Plot Area,Plot area 419(350.34 sq.m.),4,4,3+,0,"F-5/10, Sector 26 Gurgaon, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",On the lookout for a spacious house in gurgaon...,[],"['Maintenance Staff', 'Park', 'Visitor Parking...",NaN
883,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,9.00,21251,(521 sq.m.) Plot Area,Plot area 5605(520.72 sq.m.)Built Up area: 520...,4,4,3+,3,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,South-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",A lifestyle designed to satiate all your sense...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Safety4 out of 5', ..."
896,12 Bedroom House for sale in Uppals Southend,uppal southend,6.75,290948,(22 sq.m.) Plot Area,Plot area 232(21.55 sq.m.),12,12,3+,4,"Uppals Southend, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [50]:
houses['facing'].value_counts()

facing
East          176
North-East    156
North         107
West           72
North-West     43
South-East     37
South          33
South-West     24
Name: count, dtype: int64

In [51]:
houses['facing'].isna().sum()

297

In [52]:
houses['facing'].fillna('NA',inplace=True)

In [53]:
houses['area'] = round((houses['price']*10000000)/houses['price_per_sqft'])

In [54]:
houses.insert(loc=1,column='property_type',value='house')

In [55]:
houses.sample(3)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
786,6 Bedroom House for sale in Sector 67 Gurgaon,house,ireo victory valley,8.0,22222,3600.0,Plot area 400(334.45 sq.m.),6,7,3+,4,"126, Sector 67 Gurgaon, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",This villa is gated community near by reputed ...,"['6 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Safety4 out of 5', ..."
696,4 Bedroom House for sale in DLF Phase 1,house,dlf city plots,12.5,38580,3240.0,Plot area 360(301.01 sq.m.),4,5,2,2,"Def108, DLF Phase 1, Gurgaon, Haryana",2.0,North-East,5 to 10 Year Old,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...","4 bhk park facing, north east facing at very p...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
428,1 Bedroom House for sale in Ashok Vihar Phase ...,house,nan,1.0,6667,1500.0,Built Up area: 1500 (139.35 sq.m.),1,1,0,0,"Ashok Vihar Phase 3 Extension Block H, Ashok V...",1.0,NA,undefined,"['Palam triangle', 'Palam Vihar Vyapar kendra'...",1bhk villa for resale in ashok vihar phase 3 e...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."

In [56]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 945 entries, 0 to 967
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    945 non-null    object
 1   property_type    945 non-null    object
 2   society          945 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    int64
 5   area             945 non-null    float64
 6   areaWithType     945 non-null    object
 7   bedRoom          945 non-null    int64
 8   bathroom         945 non-null    int64
 9   balcony          945 non-null    object
 10  additionalRoom   945 non-null    int64
 11  address          940 non-null    object
 12  floorNum         926 non-null    float64
 13  facing           945 non-null    object
 14  agePossession    945 non-null    object
 15  nearbyLocations  830 non-null    object
 16  description      945 non-null    object
 17  furnishDetails   715 non-null    object
 18  features         647 non-null    object
 19  rating           825 non-null    object
dtypes: float64(3), int64(4), object(13)
memory usage: 155.0+ KB

In [57]:
houses.shape

(945, 20)

In [58]:
houses.to_csv('cleaned_houses.csv')